name: Generate Tfdocs
on:
  - pull_request
jobs:
  tfdocs:
    uses: montblu/github-actions/.github/workflows/tfdocs.yaml@main
    with:
      module: "[inception, k8s-connector, deployment-process]"
